### ISSUE TITLE
gulp --production error

### ISSUE THREAD

**Issue by razzaghi** [silverbux/laravel-angular-admin#50]
**Hi

I got error on running command gulp --production

this is error :**

module.js:338
    throw err;
    ^
Error: Cannot find module 'core-js/library/fn/array/from'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\Projects\Laravel\dializSheet\node_modules\karma\lib\middleware\source_files.js:1:74)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\Projects\Laravel\dializSheet\node_modules\karma\lib\web-server.js:12:29)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by silverbux** [comment]
try deleting node_modules folder and do a ```npm install``` again.
