### ISSUE TITLE
Problem running the "Gulp" part of the install

### ISSUE THREAD

**Issue by strikermdd** [silverbux/laravel-angular-admin#53]
when i run the last command of the install steps. It gives me this error:

Saving To...
   - public/assets/vendor/angular/zone

[01:38:25] Finished 'copy' after 3.05 ms
[01:38:25] Starting 'typescript'...
[01:38:25] 'typescript' errored after 8.23 ms
[01:38:25] Error in plugin 'gulp-concat'
Message:
    Missing file option for gulp-concat
[01:38:25] Error in plugin 'run-sequence(typescript)'
Error
    at finish (/var/www/mydirectory/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/var/www/mydirectory/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/var/www/mydirectory/node_modules/orchestrator/index.js:264:8)
    at /var/www/mydirectory/node_modules/orchestrator/index.js:275:23
    at finish (/var/www/mydirectory/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/var/www/mydirectory/node_modules/orchestrator/lib/runTask.js:36:10)
    at Gulp.Orchestrator._runTask (/var/www/mydirectory/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/var/www/mydirectory/node_modules/orchestrator/index.js:214:10)
/var/www/mydirectory/node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661: Cannot re-export name that is not defined in the module.

I'm using Ubuntu Server 16.04 LTS.

**Comment by silverbux** [comment]
hi, i just noticed on the last line you are using angular2?
```
/var/www/mydirectory/node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661: Cannot re-export name that is not defined in the module.
```
is this a fresh install?
